#!/bin/bash
# ci_pre_xcodebuild.sh
# Xcode Cloud pre-build script — generates Secrets.xcconfig from
# environment variables configured in Xcode Cloud settings.
#
# Required Xcode Cloud environment variables:
#   SUPABASE_URL        — e.g. https://octpebjxadbufiplgjqg.supabase.co
#   SUPABASE_ANON_KEY   — publishable Supabase anon key
#   MAPTILER_API_KEY    — MapTiler API key
#
# These must be added in Xcode Cloud → Workflow → Environment Variables.

set -euo pipefail

XCCONFIG_PATH="${CI_PRIMARY_REPOSITORY_PATH}/Secrets.xcconfig"

echo "// Secrets.xcconfig (auto-generated by ci_pre_xcodebuild.sh)" > "$XCCONFIG_PATH"
echo "// DO NOT COMMIT" >> "$XCCONFIG_PATH"
echo "" >> "$XCCONFIG_PATH"
echo "SUPABASE_URL = ${SUPABASE_URL:-}" >> "$XCCONFIG_PATH"
echo "SUPABASE_ANON_KEY = ${SUPABASE_ANON_KEY:-}" >> "$XCCONFIG_PATH"
echo "MAPTILER_API_KEY = ${MAPTILER_API_KEY:-}" >> "$XCCONFIG_PATH"

echo "[ci_pre_xcodebuild] Generated Secrets.xcconfig at $XCCONFIG_PATH"
