#
# data_loader.py
# TrackBackend
#
# Downloads GTFS data from Supabase Storage on startup, with automatic
# fallback to Docker-bundled files when Supabase is unreachable.
#
# Architecture:
#   PRIMARY  — Download fresh .tar.gz archives from Supabase Storage bucket.
#   FALLBACK — Use local files already present in app/data/ (Docker image).
#
# Data is organized into download groups (archives) so large directories
# can be fetched as a single compressed file instead of hundreds of
# individual requests.
#

from __future__ import annotations

import gzip
import hashlib
import os
import shutil
import tarfile
import tempfile
import time
from pathlib import Path
from typing import Any

import httpx

from app.utils.logger import TrackLogger

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

_DATA_DIR = Path(__file__).resolve().parent.parent.parent / "data"
_METADATA_DIR = _DATA_DIR / ".dl_meta"

SUPABASE_URL = os.environ.get("SUPABASE_URL", "")
SUPABASE_KEY = os.environ.get(
    "SUPABASE_SERVICE_KEY",
    os.environ.get(
        "SUPABASE_SERVICE_ROLE_KEY",
        os.environ.get("SUPABASE_KEY", ""),
    ),
)

BUCKET_NAME = os.environ.get("GTFS_BUCKET", "gtfs-data")
DOCKER_FALLBACK_BASE_URL = os.environ.get("GTFS_DOCKER_FALLBACK_BASE_URL", "").strip()

# Set SKIP_REMOTE_SYNC=true to bypass Supabase downloads and use only Docker-
# bundled local files.  Useful when the bucket is empty or Supabase is not
# configured (defaults to false — always try remote first).
SKIP_REMOTE_SYNC = os.environ.get("SKIP_REMOTE_SYNC", "").strip().lower() in (
    "1", "true", "yes"
)

# Timeout for downloading — generous for large files (transit_schedule.db ~100MB gzipped)
_DOWNLOAD_TIMEOUT = httpx.Timeout(connect=10.0, read=120.0, write=30.0, pool=10.0)

# ---------------------------------------------------------------------------
# Manifest: what to download and where to extract
# ---------------------------------------------------------------------------
# Each entry: (object_path_in_bucket, local_extract_dir, description)
#
# Files in the bucket are .tar.gz archives.  Each archive unpacks relative
# to its local_extract_dir.  For example "subway_core.tar.gz" contains
# shapes.txt, trips.txt, stops.txt, shape_stops.json and extracts into
# app/data/ root.

DOWNLOAD_MANIFEST: list[dict[str, Any]] = [
    {
        "object": "subway_core.tar.gz",
        "extract_to": "",           # relative to _DATA_DIR
        "description": "Subway shapes, trips, stops, shape_stops.json",
        "required_files": ["shapes.txt", "trips.txt", "shape_stops.json"],
        "critical": True,           # server can't function well without this
    },
    {
        "object": "subway_routes.tar.gz",
        "extract_to": "subway/regular_GTFS",
        "description": "Subway routes.txt for route colors/metadata",
        "required_files": ["subway/regular_GTFS/routes.txt"],
        "critical": True,
    },
    {
        "object": "subway_supplemented.tar.gz",
        "extract_to": "subway/supplemented_GTFS",
        "description": "Supplemented GTFS for iOS bundle generation",
        "required_files": ["subway/supplemented_GTFS/stop_times.txt"],
        "critical": False,
    },
    {
        "object": "lirr.tar.gz",
        "extract_to": "lirr/gtfslirr",
        "description": "LIRR GTFS static feed",
        "required_files": ["lirr/gtfslirr/shapes.txt", "lirr/gtfslirr/trips.txt"],
        "critical": True,
    },
    {
        "object": "mnr.tar.gz",
        "extract_to": "metro_north/gtfsmnr",
        "description": "Metro-North GTFS static feed",
        "required_files": ["metro_north/gtfsmnr/shapes.txt", "metro_north/gtfsmnr/trips.txt"],
        "critical": True,
    },
    {
        "object": "bus_config.tar.gz",
        "extract_to": "",
        "description": "Bus route tag overrides",
        "required_files": ["early_2026_buses_tag.json"],
        "critical": False,
    },
    {
        # ML model — uploaded explicitly via scripts/upload_model.py when
        # retrained.  Docker image always bundles the last trained pkl as a
        # fallback; this download replaces it only when a newer version has
        # been explicitly pushed to Supabase (i.e. after a local retrain).
        "object": "delay_model.tar.gz",
        "extract_to": "",           # extracts delay_model.pkl to app/data/ root
        "description": "ML LightGBM delay prediction model",
        "required_files": ["delay_model.pkl"],
        "critical": False,          # heuristic factor used if missing
    },
]

# transit_schedule.db is Docker-bundled only (863 MB raw, 170 MB gzipped —
# exceeds Supabase free-tier 50 MB upload limit).  It's a build artifact
# generated by scripts/ingest_gtfs.py and rarely changes.
LOCAL_ONLY_FILES: list[dict[str, Any]] = [
    {
        "description": "Pre-built schedule SQLite database",
        "required_files": ["transit_schedule.db"],
        "critical": False,
    },
]


# ---------------------------------------------------------------------------
# Supabase Storage helpers
# ---------------------------------------------------------------------------

def _storage_url(object_path: str) -> str:
    """Build the Supabase Storage download URL for an object."""
    base = SUPABASE_URL.rstrip("/")
    return f"{base}/storage/v1/object/{BUCKET_NAME}/{object_path}"


def _auth_headers() -> dict[str, str]:
    return {
        "apikey": SUPABASE_KEY,
        "Authorization": f"Bearer {SUPABASE_KEY}",
    }


def _etag_path(object_name: str) -> Path:
    """Local path to store the ETag for an object (skip re-download if unchanged)."""
    return _METADATA_DIR / f"{object_name}.etag"


def _read_local_etag(object_name: str) -> str | None:
    p = _etag_path(object_name)
    if p.exists():
        return p.read_text().strip()
    return None


def _write_local_etag(object_name: str, etag: str) -> None:
    _METADATA_DIR.mkdir(parents=True, exist_ok=True)
    _etag_path(object_name).write_text(etag)


def _extract_tar_archive(tmp_path: str, extract_to: Path) -> None:
    """Extract a .tar.gz archive into *extract_to* with path safety checks."""
    extract_to.mkdir(parents=True, exist_ok=True)
    with tarfile.open(tmp_path, "r:gz") as tar:
        for member in tar.getmembers():
            member_path = (extract_to / member.name).resolve()
            if not str(member_path).startswith(str(extract_to.resolve())):
                TrackLogger.warning(
                    f"[DATA] Skipping suspicious tar member: {member.name}",
                    tag="DATA",
                )
                continue
        tar.extractall(path=extract_to)


def _docker_fallback_url(object_path: str) -> str | None:
    """Build optional Docker mirror URL for GTFS archives."""
    base = DOCKER_FALLBACK_BASE_URL.rstrip("/")
    if not base:
        return None
    return f"{base}/{object_path}"


def _try_download_from_docker_fallback(
    client: httpx.Client,
    entry: dict[str, Any],
) -> bool:
    """Attempt archive download from Docker mirror URL (no auth)."""
    obj = entry["object"]
    extract_to = _DATA_DIR / entry["extract_to"] if entry["extract_to"] else _DATA_DIR
    desc = entry["description"]

    url = _docker_fallback_url(obj)
    if not url:
        return False

    try:
        t0 = time.monotonic()
        with client.stream("GET", url) as resp:
            if resp.status_code >= 400:
                TrackLogger.warning(
                    f"[DATA] {desc}: Docker fallback HTTP {resp.status_code}",
                    tag="DATA",
                )
                return False

            with tempfile.NamedTemporaryFile(suffix=".tar.gz", delete=False) as tmp:
                tmp_path = tmp.name
                downloaded = 0
                for chunk in resp.iter_bytes(chunk_size=65_536):
                    tmp.write(chunk)
                    downloaded += len(chunk)

        elapsed = time.monotonic() - t0
        size_mb = downloaded / (1024 * 1024)
        TrackLogger.info(
            f"[DATA] {desc}: downloaded {size_mb:.1f} MB from Docker fallback in {elapsed:.1f}s",
            tag="DATA",
        )

        _extract_tar_archive(tmp_path, extract_to)
        os.unlink(tmp_path)
        return True

    except (httpx.ConnectError, httpx.TimeoutException, httpx.ReadTimeout) as exc:
        TrackLogger.warning(
            f"[DATA] {desc}: Docker fallback unreachable ({type(exc).__name__})",
            tag="DATA",
        )
        return False
    except Exception as exc:
        TrackLogger.warning(
            f"[DATA] {desc}: Docker fallback failed ({exc})",
            tag="DATA",
        )
        return False


# ---------------------------------------------------------------------------
# Download + extract
# ---------------------------------------------------------------------------

def _has_required_files(entry: dict[str, Any]) -> bool:
    """Check if the required local files for a manifest entry already exist."""
    for rel in entry["required_files"]:
        if not (_DATA_DIR / rel).exists():
            return False
    return True


def _download_and_extract(
    client: httpx.Client,
    entry: dict[str, Any],
) -> tuple[bool, bool]:
    """Download a single archive from Supabase and extract it.

    Returns (available, fetched_from_remote).

    available:
        True when data is usable (downloaded, 304 up-to-date, or local fallback).
    fetched_from_remote:
        True only when the remote fetch succeeded (200/304).
    """
    obj = entry["object"]
    extract_to = _DATA_DIR / entry["extract_to"] if entry["extract_to"] else _DATA_DIR
    desc = entry["description"]

    url = _storage_url(obj)
    headers = _auth_headers()

    # Send ETag to avoid re-downloading unchanged data
    local_etag = _read_local_etag(obj)
    if local_etag:
        headers["If-None-Match"] = local_etag

    try:
        t0 = time.monotonic()
        with client.stream("GET", url, headers=headers) as resp:
            if resp.status_code == 304:
                TrackLogger.info(
                    f"[DATA] {desc}: up-to-date (ETag match)", tag="DATA"
                )
                return True, True

            if resp.status_code >= 400:
                # Read the first 400 bytes of the error body for diagnostics.
                # Supabase Storage returns HTTP 400 (not 404) with a JSON body
                # of {"statusCode":"404","error":"not_found",...} when an
                # object doesn't exist, so we surface the real message.
                error_chunks: list[bytes] = []
                for _chunk in resp.iter_bytes():
                    error_chunks.append(_chunk)
                    if sum(len(c) for c in error_chunks) >= 400:
                        break
                raw_err = b"".join(error_chunks).decode(errors="replace")
                try:
                    import json as _json
                    err_data = _json.loads(raw_err)
                    err_msg = err_data.get("message") or err_data.get("error") or raw_err[:120]
                except Exception:
                    err_msg = raw_err[:120]

                is_not_found = (
                    resp.status_code == 404
                    or "not_found" in raw_err
                    or "Object not found" in raw_err
                )
                status_label = f"HTTP {resp.status_code} (not found)" if is_not_found else f"HTTP {resp.status_code}"

                docker_ok = _try_download_from_docker_fallback(client, entry)
                if docker_ok:
                    return True, True
                fallback_ok = _has_required_files(entry)
                TrackLogger.warning(
                    f"[DATA] {desc}: {status_label} — {err_msg}"
                    + (" — using local fallback" if fallback_ok else ""),
                    tag="DATA",
                )
                return fallback_ok, False

            # Stream to a temp file, then extract
            etag = resp.headers.get("etag", "")
            content_length = int(resp.headers.get("content-length", 0))

            with tempfile.NamedTemporaryFile(
                suffix=".tar.gz", delete=False
            ) as tmp:
                tmp_path = tmp.name
                downloaded = 0
                for chunk in resp.iter_bytes(chunk_size=65_536):
                    tmp.write(chunk)
                    downloaded += len(chunk)

        elapsed = time.monotonic() - t0
        size_mb = downloaded / (1024 * 1024)
        TrackLogger.info(
            f"[DATA] {desc}: downloaded {size_mb:.1f} MB in {elapsed:.1f}s",
            tag="DATA",
        )

        # Extract archive
        _extract_tar_archive(tmp_path, extract_to)

        os.unlink(tmp_path)

        # Save ETag for next time
        if etag:
            _write_local_etag(obj, etag)

        return True, True

    except (httpx.ConnectError, httpx.TimeoutException, httpx.ReadTimeout) as exc:
        docker_ok = _try_download_from_docker_fallback(client, entry)
        if docker_ok:
            return True, True
        fallback_ok = _has_required_files(entry)
        TrackLogger.warning(
            f"[DATA] {desc}: Supabase unreachable ({type(exc).__name__})"
            + (" — using local fallback" if fallback_ok else ""),
            tag="DATA",
        )
        return fallback_ok, False
    except Exception as exc:
        docker_ok = _try_download_from_docker_fallback(client, entry)
        if docker_ok:
            return True, True
        fallback_ok = _has_required_files(entry)
        TrackLogger.error(
            f"[DATA] {desc}: unexpected error — {exc}", tag="DATA"
        )
        return fallback_ok, False


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

async def ensure_data_available() -> dict[str, bool]:
    """Download GTFS data from Supabase Storage with Docker-bundled fallback.

    Called once at startup.  Returns a dict of {description: available?}
    so the caller can log which data is ready.

    Flow:
        1. For each archive in the manifest, try to download from Supabase.
        2. If download succeeds, extract into app/data/.
        3. If Supabase is down or file missing, check if local files exist
           (Docker-bundled fallback).
        4. Log results — critical failures are logged as errors.
    """
    results: dict[str, bool] = {}

    TrackLogger.info("[DATA] Starting GTFS data sync from Supabase Storage...", tag="DATA")
    t_total = time.monotonic()

    # Use sync httpx inside an executor to avoid blocking the event loop
    # while streaming large downloads.
    import asyncio
    loop = asyncio.get_running_loop()
    results = await loop.run_in_executor(None, _sync_download_all)

    elapsed = time.monotonic() - t_total

    ready = sum(1 for v in results.values() if v)
    total = len(results)
    failed = [k for k, v in results.items() if not v]

    if failed:
        TrackLogger.error(
            f"[DATA] GTFS sync done in {elapsed:.1f}s — {ready}/{total} ready. "
            f"MISSING: {', '.join(failed)}",
            tag="DATA",
        )
    else:
        TrackLogger.info(
            f"[DATA] GTFS sync done in {elapsed:.1f}s — all {total} data groups ready.",
            tag="DATA",
        )

    return results


def _sync_download_all() -> dict[str, bool]:
    """Synchronous worker that downloads all manifest entries."""
    results: dict[str, bool] = {}
    remote_failures: list[str] = []

    # ------------------------------------------------------------------
    # SKIP_REMOTE_SYNC fast-path: use only Docker-bundled local files.
    # Activate by setting SKIP_REMOTE_SYNC=true in the environment when
    # the Supabase bucket is empty or remote access is not configured.
    # ------------------------------------------------------------------
    if SKIP_REMOTE_SYNC:
        TrackLogger.info(
            "[DATA] SKIP_REMOTE_SYNC=true — skipping Supabase download, "
            "using local fallback for all data groups.",
            tag="DATA",
        )
        for entry in DOWNLOAD_MANIFEST:
            ok = _has_required_files(entry)
            results[entry["description"]] = ok
            if not ok and entry.get("critical"):
                TrackLogger.error(
                    f"[DATA] CRITICAL: {entry['description']} not found locally! "
                    "Some endpoints will fail.",
                    tag="DATA",
                )
        return results

    with httpx.Client(timeout=_DOWNLOAD_TIMEOUT, follow_redirects=True) as client:
        for entry in DOWNLOAD_MANIFEST:
            ok, fetched_from_remote = _download_and_extract(client, entry)
            results[entry["description"]] = ok

            if ok and not fetched_from_remote:
                remote_failures.append(entry["description"])

            if not ok and entry.get("critical"):
                TrackLogger.error(
                    f"[DATA] CRITICAL: {entry['description']} unavailable! "
                    "Some endpoints will fail.",
                    tag="DATA",
                )

    if remote_failures:
        failed_list = ", ".join(remote_failures[:3])
        extra = "" if len(remote_failures) <= 3 else f", +{len(remote_failures) - 3} more"
        all_failed = len(remote_failures) == len(DOWNLOAD_MANIFEST)
        hint = (
            " — set SKIP_REMOTE_SYNC=true to use only local data and silence these warnings"
            if all_failed else ""
        )
        TrackLogger.warning(
            f"[DATA] Remote sync failed for {len(remote_failures)} data groups; "
            f"served via local fallback: {failed_list}{extra}{hint}",
            tag="DATA",
        )

    return results


def check_local_data_status() -> dict[str, bool]:
    """Check which data groups have their required files present locally.

    Useful for health checks without triggering downloads.
    """
    status = {
        entry["description"]: _has_required_files(entry)
        for entry in DOWNLOAD_MANIFEST
    }
    # Include Docker-bundled-only files in the status check
    for entry in LOCAL_ONLY_FILES:
        status[entry["description"]] = _has_required_files(entry)
    return status
