-- MetroMind chat threads + messages.
--
-- Mirrors the SQLite schema in app/metromind/thread_store.py. Written
-- from the FastAPI backend via PostgREST using the service-role key.
-- The iOS app never reads or writes directly; it goes through
-- /metromind/chat (SSE) and /metromind/threads/{id}.

create table if not exists public.metromind_threads (
  id          text primary key,
  created_at  timestamptz not null default timezone('utc', now()),
  updated_at  timestamptz not null default timezone('utc', now()),
  title       text
);

create index if not exists idx_metromind_threads_updated
  on public.metromind_threads (updated_at desc);

create table if not exists public.metromind_messages (
  id              bigint generated by default as identity primary key,
  thread_id       text not null references public.metromind_threads(id) on delete cascade,
  role            text not null check (role in ('user', 'assistant', 'system')),
  content         text not null,
  created_at      timestamptz not null default timezone('utc', now()),
  image_data_url  text
);

create index if not exists idx_metromind_messages_thread_created
  on public.metromind_messages (thread_id, created_at);

create index if not exists idx_metromind_messages_thread_id_desc
  on public.metromind_messages (thread_id, id desc);

-- Lock down: backend service-role key bypasses RLS, end-user JWTs
-- have no access. Conversation history is sensitive (location, plans).
alter table public.metromind_threads  enable row level security;
alter table public.metromind_messages enable row level security;
