-- Trip configuration preferences per user.
-- Stores transit mode filters, walking preferences, accessibility,
-- and routing priority so the planner can tailor results.

create table if not exists public.trip_configurations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,

  -- Routing priority: "quick" (default) | "fewer_transfers" | "less_walking"
  priority text not null default 'quick'
    check (priority in ('quick', 'fewer_transfers', 'less_walking')),

  -- Transit mode toggles (all default ON)
  mode_subway boolean not null default true,
  mode_bus boolean not null default true,
  mode_lirr boolean not null default false,
  mode_mnr boolean not null default false,

  -- Accessibility: prefer ADA-accessible stations/stops
  accessibility_priority boolean not null default false,

  -- Walking preference: 0.0 = walk as little as possible, 1.0 = willing to walk more
  -- 0.5 is the default / balanced setting
  walk_preference real not null default 0.5
    check (walk_preference >= 0.0 and walk_preference <= 1.0),

  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),

  constraint trip_configurations_user_unique unique (user_id)
);

create index if not exists idx_trip_configurations_user
  on public.trip_configurations (user_id);

-- Auto-update updated_at on changes
drop trigger if exists set_trip_configurations_updated_at on public.trip_configurations;
create trigger set_trip_configurations_updated_at
before update on public.trip_configurations
for each row
execute function public.engine_set_updated_at();

-- Row-level security: users can only access their own row
alter table public.trip_configurations enable row level security;

drop policy if exists "trip configurations own rows" on public.trip_configurations;
create policy "trip configurations own rows"
on public.trip_configurations
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);
