create or replace function public.engine_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.engine_saved_places (
  id bigint generated by default as identity primary key,
  user_id text not null,
  label text not null check (char_length(trim(label)) > 0),
  kind text not null check (char_length(trim(kind)) > 0),
  lat double precision not null,
  lon double precision not null,
  address text,
  icon text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  last_used_at timestamptz
);

create index if not exists idx_engine_saved_places_user
  on public.engine_saved_places (user_id, kind, updated_at desc, label);

create table if not exists public.engine_saved_trips (
  id bigint generated by default as identity primary key,
  user_id text not null,
  name text not null check (char_length(trim(name)) > 0),
  origin_label text not null check (char_length(trim(origin_label)) > 0),
  origin_lat double precision not null,
  origin_lon double precision not null,
  destination_label text not null check (char_length(trim(destination_label)) > 0),
  destination_lat double precision not null,
  destination_lon double precision not null,
  preferred_departure_hour smallint check (
    preferred_departure_hour is null
    or (preferred_departure_hour between 0 and 23)
  ),
  preferred_arrival_hour smallint check (
    preferred_arrival_hour is null
    or (preferred_arrival_hour between 0 and 23)
  ),
  preferred_modes jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  last_used_at timestamptz
);

create index if not exists idx_engine_saved_trips_user
  on public.engine_saved_trips (user_id, updated_at desc, name);

create table if not exists public.engine_recent_trips (
  id bigint generated by default as identity primary key,
  user_id text not null,
  origin_label text not null check (char_length(trim(origin_label)) > 0),
  origin_lat double precision not null,
  origin_lon double precision not null,
  destination_label text not null check (char_length(trim(destination_label)) > 0),
  destination_lat double precision not null,
  destination_lon double precision not null,
  requested_at timestamptz not null default timezone('utc', now()),
  leave_at_ts bigint not null,
  arrive_at_ts bigint not null,
  summary text not null,
  route_tokens jsonb not null default '[]'::jsonb
);

create index if not exists idx_engine_recent_trips_user
  on public.engine_recent_trips (user_id, requested_at desc, id desc);

create table if not exists public.engine_calendar_events (
  id bigint generated by default as identity primary key,
  user_id text not null,
  external_id text not null,
  title text not null check (char_length(trim(title)) > 0),
  location_label text not null check (char_length(trim(location_label)) > 0),
  lat double precision,
  lon double precision,
  starts_at timestamptz not null,
  ends_at timestamptz,
  notes text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint engine_calendar_events_user_external_unique unique (user_id, external_id)
);

create index if not exists idx_engine_calendar_events_user
  on public.engine_calendar_events (user_id, starts_at asc);

drop trigger if exists set_engine_saved_places_updated_at on public.engine_saved_places;
create trigger set_engine_saved_places_updated_at
before update on public.engine_saved_places
for each row
execute function public.engine_set_updated_at();

drop trigger if exists set_engine_saved_trips_updated_at on public.engine_saved_trips;
create trigger set_engine_saved_trips_updated_at
before update on public.engine_saved_trips
for each row
execute function public.engine_set_updated_at();

drop trigger if exists set_engine_calendar_events_updated_at on public.engine_calendar_events;
create trigger set_engine_calendar_events_updated_at
before update on public.engine_calendar_events
for each row
execute function public.engine_set_updated_at();

create or replace function public.engine_trim_recent_trips(
  p_user_id text,
  p_keep_rows integer default 100
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_deleted integer := 0;
begin
  delete from public.engine_recent_trips
  where user_id = p_user_id
    and id in (
      select id
      from public.engine_recent_trips
      where user_id = p_user_id
      order by requested_at desc, id desc
      offset greatest(p_keep_rows, 0)
    );

  get diagnostics v_deleted = row_count;
  return v_deleted;
end;
$$;

create or replace function public.engine_recent_destinations(
  p_user_id text,
  p_limit integer default 20
)
returns table (
  label text,
  lat double precision,
  lon double precision,
  trip_count bigint,
  last_used_at bigint
)
language sql
stable
security definer
set search_path = public
as $$
  with grouped as (
    select
      destination_label as label,
      round(destination_lat::numeric, 4) as rounded_lat,
      round(destination_lon::numeric, 4) as rounded_lon,
      avg(destination_lat)::double precision as lat,
      avg(destination_lon)::double precision as lon,
      count(*)::bigint as trip_count,
      max(requested_at) as last_used_at
    from public.engine_recent_trips
    where user_id = p_user_id
    group by destination_label,
             round(destination_lat::numeric, 4),
             round(destination_lon::numeric, 4)
  )
  select
    grouped.label,
    grouped.lat,
    grouped.lon,
    grouped.trip_count,
    extract(epoch from grouped.last_used_at)::bigint as last_used_at
  from grouped
  order by grouped.trip_count desc, grouped.last_used_at desc
  limit greatest(p_limit, 0);
$$;

alter table public.engine_saved_places enable row level security;
alter table public.engine_saved_trips enable row level security;
alter table public.engine_recent_trips enable row level security;
alter table public.engine_calendar_events enable row level security;

drop policy if exists "engine saved places own rows" on public.engine_saved_places;
create policy "engine saved places own rows"
on public.engine_saved_places
for all
to authenticated
using (auth.uid()::text = user_id)
with check (auth.uid()::text = user_id);

drop policy if exists "engine saved trips own rows" on public.engine_saved_trips;
create policy "engine saved trips own rows"
on public.engine_saved_trips
for all
to authenticated
using (auth.uid()::text = user_id)
with check (auth.uid()::text = user_id);

drop policy if exists "engine recent trips own rows" on public.engine_recent_trips;
create policy "engine recent trips own rows"
on public.engine_recent_trips
for all
to authenticated
using (auth.uid()::text = user_id)
with check (auth.uid()::text = user_id);

drop policy if exists "engine calendar events own rows" on public.engine_calendar_events;
create policy "engine calendar events own rows"
on public.engine_calendar_events
for all
to authenticated
using (auth.uid()::text = user_id)
with check (auth.uid()::text = user_id);

grant execute on function public.engine_trim_recent_trips(text, integer) to authenticated, service_role;
grant execute on function public.engine_recent_destinations(text, integer) to authenticated, service_role;
