-- ─────────────────────────────────────────────────────────────────────────────
-- Track analytics layer: TikTok-grade behavioral telemetry
--
-- Design goals
-- • Backend (service role) is the SOLE writer.  iOS never POSTs directly.
-- • Per-user reads via RLS using auth.uid() — users can only see their own data.
-- • Tables denormalised for cheap funnels & cohorts (no joins on hot paths).
-- • All timestamps UTC, all jsonb fields default '{}'::jsonb / '[]'::jsonb.
-- • Idempotent: safe to re-run if Supabase ever rolls back.
--
-- Identity model
-- • uuid user_id → references auth.users(id)  (mirrors profiles/favorites).
-- • Apple-sub text identities (engine_*) are kept as-is and not touched here.
--
-- Cleanup
-- • Removes the 1 smoke-test feedback row from the previous migration.
-- ─────────────────────────────────────────────────────────────────────────────

-- 0. Smoke-test cleanup ------------------------------------------------------

delete from public.metromind_feedback
 where user_prompt = 'hi'
   and assistant_text = 'hi back';


-- 1. Helper: timestamptz updated_at trigger (idempotent) ---------------------

create or replace function public.analytics_set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;


-- 2. user_sessions ───────────────────────────────────────────────────────────
-- One row per foreground session (≤ 30 s gap merges into prior session).

create table if not exists public.user_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  started_at timestamptz not null default timezone('utc', now()),
  ended_at timestamptz,
  last_active_at timestamptz not null default timezone('utc', now()),
  app_version text,
  build text,
  os_version text,
  device_model text,
  locale text,
  timezone text,
  network_type text,                         -- 'wifi' | 'cellular' | 'none'
  foreground_seconds integer not null default 0,
  screens_viewed integer not null default 0,
  events_count integer not null default 0,
  entry_screen text,
  entry_source text,                         -- 'cold' | 'warm' | 'push' | 'shortcut' | 'widget'
  push_notification_id text,
  initial_lat double precision,
  initial_lon double precision,
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_user_sessions_user_started
  on public.user_sessions (user_id, started_at desc);
create index if not exists idx_user_sessions_active
  on public.user_sessions (user_id, last_active_at desc) where ended_at is null;

drop trigger if exists set_user_sessions_updated_at on public.user_sessions;
create trigger set_user_sessions_updated_at
  before update on public.user_sessions
  for each row execute function public.analytics_set_updated_at();


-- 3. analytics_events ────────────────────────────────────────────────────────
-- Generic event firehose (everything not worth its own table).

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  session_id uuid references public.user_sessions(id) on delete set null,
  event_name text not null check (char_length(event_name) between 1 and 80),
  properties jsonb not null default '{}'::jsonb,
  screen text,
  occurred_at timestamptz not null default timezone('utc', now()),
  app_version text,
  os_version text,
  device_model text,
  network_type text,
  lat double precision,
  lon double precision,
  ingested_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_analytics_events_user_time
  on public.analytics_events (user_id, occurred_at desc);
create index if not exists idx_analytics_events_name_time
  on public.analytics_events (event_name, occurred_at desc);
create index if not exists idx_analytics_events_session
  on public.analytics_events (session_id, occurred_at desc);
create index if not exists idx_analytics_events_props_gin
  on public.analytics_events using gin (properties);


-- 4. screen_views ────────────────────────────────────────────────────────────
-- Denormalised funnel/dwell table (separate from events for cheap aggregates).

create table if not exists public.screen_views (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  session_id uuid references public.user_sessions(id) on delete set null,
  screen text not null,
  previous_screen text,
  entered_at timestamptz not null default timezone('utc', now()),
  exited_at timestamptz,
  duration_ms integer,
  scroll_depth_pct smallint check (scroll_depth_pct is null or scroll_depth_pct between 0 and 100),
  interactions_count integer not null default 0,
  reached_via text,                          -- 'tab' | 'push' | 'deeplink' | 'back' | 'modal' | 'unknown'
  app_version text
);

create index if not exists idx_screen_views_user_time
  on public.screen_views (user_id, entered_at desc);
create index if not exists idx_screen_views_screen_time
  on public.screen_views (screen, entered_at desc);
create index if not exists idx_screen_views_session
  on public.screen_views (session_id, entered_at);


-- 5. search_queries ──────────────────────────────────────────────────────────
-- Every search box submission anywhere in the app.

create table if not exists public.search_queries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  session_id uuid references public.user_sessions(id) on delete set null,
  source text not null check (source in (
    'home','nearby','chat','trip_planner','route_picker','map','widget','other'
  )),
  query text not null,
  query_normalized text generated always as (lower(trim(query))) stored,
  results_count integer,
  picked_index integer,                      -- 0-based
  picked_id text,                            -- station_id / route_id / poi
  picked_kind text,                          -- 'station' | 'route' | 'place' | 'address'
  latency_ms integer,
  abandoned boolean not null default false,
  origin_lat double precision,
  origin_lon double precision,
  occurred_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_search_queries_user_time
  on public.search_queries (user_id, occurred_at desc);
create index if not exists idx_search_queries_normalized
  on public.search_queries (query_normalized);
create index if not exists idx_search_queries_source
  on public.search_queries (source, occurred_at desc);


-- 6. route_engagements ───────────────────────────────────────────────────────
-- Anything the user does with a route/trip/option.

create table if not exists public.route_engagements (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  session_id uuid references public.user_sessions(id) on delete set null,
  action text not null check (action in (
    'impression','view_details','select','start_tracking','complete',
    'abandon','share','dismiss','swap_to_alternative','reroute'
  )),
  route_id text,
  route_display_name text,
  mode text,                                 -- 'subway' | 'bus' | 'lirr' | 'mnr' | 'walk' | 'multimodal'
  origin_label text,
  origin_lat double precision,
  origin_lon double precision,
  destination_label text,
  destination_lat double precision,
  destination_lon double precision,
  eta_seconds integer,
  transfers_count smallint,
  walk_meters integer,
  predicted_arrival timestamptz,
  actual_arrival timestamptz,
  alternatives_offered smallint,             -- how many other options were on screen
  position_in_list smallint,                 -- index of the chosen option
  source_screen text,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_route_engagements_user_time
  on public.route_engagements (user_id, occurred_at desc);
create index if not exists idx_route_engagements_route
  on public.route_engagements (route_id, action, occurred_at desc);
create index if not exists idx_route_engagements_action
  on public.route_engagements (action, occurred_at desc);


-- 7. map_interactions ────────────────────────────────────────────────────────
-- Pan / zoom / station tap / line tap / long press.

create table if not exists public.map_interactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  session_id uuid references public.user_sessions(id) on delete set null,
  kind text not null check (kind in (
    'pan','zoom','station_tap','line_tap','long_press','annotation_tap',
    'cluster_tap','recenter','rotate','tilt'
  )),
  zoom_level real,
  center_lat double precision,
  center_lon double precision,
  target_id text,
  target_kind text,                          -- 'station' | 'route' | 'bus_stop' | 'cluster'
  occurred_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_map_interactions_user_time
  on public.map_interactions (user_id, occurred_at desc);
create index if not exists idx_map_interactions_kind
  on public.map_interactions (kind, occurred_at desc);


-- 8. error_events ────────────────────────────────────────────────────────────
-- Client-side errors, decode failures, network failures, asserts.

create table if not exists public.error_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  session_id uuid references public.user_sessions(id) on delete set null,
  kind text not null,                        -- 'network' | 'decode' | 'assert' | 'tts' | 'auth' | ...
  severity text not null default 'error' check (severity in ('debug','info','warning','error','fatal')),
  message text not null,
  stack text,
  screen text,
  endpoint text,
  http_status integer,
  app_version text,
  os_version text,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_error_events_user_time
  on public.error_events (user_id, occurred_at desc);
create index if not exists idx_error_events_kind_time
  on public.error_events (kind, occurred_at desc);
create index if not exists idx_error_events_severity
  on public.error_events (severity, occurred_at desc);


-- 9. performance_metrics ─────────────────────────────────────────────────────
-- API latency, render time, cold-start, warm-start.

create table if not exists public.performance_metrics (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  session_id uuid references public.user_sessions(id) on delete set null,
  kind text not null check (kind in (
    'api','render','cold_start','warm_start','image_load','tts_synth','llm_first_token','llm_total'
  )),
  name text not null,                        -- e.g. '/nearby/grouped' or 'HomeView.body'
  duration_ms integer not null check (duration_ms >= 0),
  http_status integer,
  payload_bytes integer,
  cache_hit boolean,
  network_type text,
  occurred_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_perf_user_time
  on public.performance_metrics (user_id, occurred_at desc);
create index if not exists idx_perf_kind_name_time
  on public.performance_metrics (kind, name, occurred_at desc);


-- 10. notification_events ────────────────────────────────────────────────────
-- Push notification lifecycle (received / opened / dismissed).

create table if not exists public.notification_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  session_id uuid references public.user_sessions(id) on delete set null,
  kind text not null check (kind in ('received','opened','dismissed','action_tapped')),
  notification_id text,
  category text,                             -- 'arrival' | 'service_alert' | 'commute_reminder' | 'metromind' | ...
  action_id text,
  payload jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_notification_events_user_time
  on public.notification_events (user_id, occurred_at desc);
create index if not exists idx_notification_events_kind
  on public.notification_events (kind, occurred_at desc);


-- 11. feature_flag_exposures ─────────────────────────────────────────────────
-- A/B test variant assignment ledger (for cohort splits / experiments).

create table if not exists public.feature_flag_exposures (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  session_id uuid references public.user_sessions(id) on delete set null,
  flag_key text not null,
  variant text not null,
  context jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default timezone('utc', now()),
  unique (user_id, flag_key, variant)
);

create index if not exists idx_ff_exposures_user
  on public.feature_flag_exposures (user_id, flag_key);
create index if not exists idx_ff_exposures_flag
  on public.feature_flag_exposures (flag_key, variant);


-- ─────────────────────────────────────────────────────────────────────────────
-- 12. RLS — analytics tables: per-user SELECT, service-role-only writes
-- ─────────────────────────────────────────────────────────────────────────────

do $$
declare
  t text;
begin
  for t in select unnest(array[
    'user_sessions','analytics_events','screen_views','search_queries',
    'route_engagements','map_interactions','error_events',
    'performance_metrics','notification_events','feature_flag_exposures'
  ]) loop
    execute format('alter table public.%I enable row level security;', t);
    execute format('drop policy if exists "%s_owner_read" on public.%I;', t, t);
    execute format($p$create policy "%s_owner_read" on public.%I
                       for select to authenticated
                       using (auth.uid() = user_id);$p$, t, t);
  end loop;
end $$;


-- ─────────────────────────────────────────────────────────────────────────────
-- 13. RLS audit — ensure every existing public table has RLS enabled
--     (service-role bypasses RLS automatically; this just slams the door
--     on anyone with the anon key trying to read raw rows).
-- ─────────────────────────────────────────────────────────────────────────────

do $$
declare
  t text;
begin
  for t in
    select c.relname
      from pg_class c
      join pg_namespace n on n.oid = c.relnamespace
     where n.nspname = 'public'
       and c.relkind = 'r'
       and c.relrowsecurity = false
  loop
    execute format('alter table public.%I enable row level security;', t);
    raise notice 'enabled RLS on public.%', t;
  end loop;
end $$;


-- ─────────────────────────────────────────────────────────────────────────────
-- 14. Per-user SELECT policies for uuid-keyed user-owned tables that didn't
--     have one.  (We can't add auth.uid() policies to engine_* tables because
--     they store text Apple-sub identities, not uuids — those remain
--     service-role-only, which is correct given iOS goes through the backend.)
-- ─────────────────────────────────────────────────────────────────────────────

do $$
declare
  t text;
begin
  for t in select unnest(array[
    'profiles','favorites','schedules','user_settings',
    'commute_patterns','route_interactions','trip_configurations',
    'metromind_threads','metromind_feedback'
  ]) loop
    -- profiles uses 'id' as the FK to auth.users, the rest use 'user_id'
    if t = 'profiles' then
      execute format('drop policy if exists "%s_owner_read" on public.%I;', t, t);
      execute format($p$create policy "%s_owner_read" on public.%I
                         for select to authenticated
                         using (auth.uid() = id);$p$, t, t);
    elsif t = 'metromind_threads' or t = 'metromind_feedback' then
      -- These tables don't currently carry a user_id column.
      -- Keep them service-role-only; backend filters by thread_id.
      continue;
    else
      execute format('drop policy if exists "%s_owner_read" on public.%I;', t, t);
      execute format($p$create policy "%s_owner_read" on public.%I
                         for select to authenticated
                         using (auth.uid() = user_id);$p$, t, t);
    end if;
  end loop;
end $$;
