-- MetroMind chat feedback (thumbs up / down on assistant replies).
--
-- Written from the FastAPI backend via PostgREST using the service-role
-- key. The iOS app never inserts directly; it POSTs to
-- /metromind/feedback which proxies the row.

create table if not exists public.metromind_feedback (
  id              bigint generated by default as identity primary key,
  created_at      timestamptz not null default timezone('utc', now()),
  rating          smallint not null check (rating in (-1, 1)),
  thread_id       text,
  client_msg_id   text,
  user_prompt     text,
  assistant_text  text,
  reason          text,
  app_version     text,
  model_used      text
);

create index if not exists idx_metromind_feedback_created
  on public.metromind_feedback (created_at desc);

create index if not exists idx_metromind_feedback_rating
  on public.metromind_feedback (rating, created_at desc);

create index if not exists idx_metromind_feedback_thread
  on public.metromind_feedback (thread_id, created_at desc);

-- Row Level Security: lock the table down. Backend service-role key
-- bypasses RLS, end-user JWTs cannot read or write this table.
alter table public.metromind_feedback enable row level security;

-- No policies = no access for anon/authenticated roles.
